version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - v1-{{ checksum "reflow.cabal" }}-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: ./bin/setup
      - save_cache:
          name: Cache Dependencies
          key: v1-{{ checksum "reflow.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Run tests
          command: ./bin/test
